spring.application.name=nmichail

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}

spring.datasource.username=postgres
spring.datasource.password=root

logging.level.org.flywaydb=INFO

taxi.pricing.tariff-per-km=50.0

taxi.security.jwt.secret=8kSNTs27NV2rUFT4nMtMxtWzOzVhVKaah8CncH522LW
taxi.security.jwt.ttl-seconds=3600

taxi.security.default-admin.username=admin
taxi.security.default-admin.password=admin

spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.show-actuator=false
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

taxi.notification.enabled=true
taxi.notification.workers=4
taxi.notification.sleep-ms=50